version: "3"

services:

  git_test:
    build:
      context: ./git_test
    volumes:
      - ~/.ssh:/ssh
      # - type: bind
      #   source: '~/.ssh'
      #   target: '/ssh'

  node_tset:
    build:
      context: ./node-test
    ports:
      - "3000:3000"
    volumes:
      - ./node-test:/user/src/app/
    networks:
      - publick_net

  anguar_test:
    build:
      context: ./angular-test
      args:
        API_URL:  "http://localhost:3000/"
    ports:
        - "4200:4200"
        - "49153:49153"
    volumes:
      - ./angular-test:/app/
    networks:
      - publick_net

networks:
  publick_net:
    driver: bridge
  # webnet:
